In [1]:
import pandas as pd

In [6]:
data = {'name':['sudh','krish','hitesh','tulesko'],'salary':[100,200,300,400],'mail_id':['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       'add':['bir','bir','bir','mum']}

In [40]:
pd.DataFrame(data)

name  salary             mail_id  add
0     sudh     100     sudh@ineuron.ai  bir
1    krish     200    krish@ineuron.ai  bir
2   hitesh     300   hitesh@ineuron.ai  bir
3  tulesko     400  tulesko@ineuron.ai  mum

In [32]:
pd.DataFrame(data,columns=[0,1,2])

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [46]:
df = pd.DataFrame(data)

In [47]:
df

name  salary             mail_id  add
0     sudh     100     sudh@ineuron.ai  bir
1    krish     200    krish@ineuron.ai  bir
2   hitesh     300   hitesh@ineuron.ai  bir
3  tulesko     400  tulesko@ineuron.ai  mum

In [33]:
#df = pd.DataFrame(data,index=[5,6,7,8])

In [37]:
df.loc[7:8]

name  salary             mail_id  add
7   hitesh     300   hitesh@ineuron.ai  bir
8  tulesko     400  tulesko@ineuron.ai  mum

In [38]:
df.iloc[7:8]

Empty DataFrame
Columns: [name, salary, mail_id, add]
Index: []

In [39]:
df.iloc[2:4]

name  salary             mail_id  add
7   hitesh     300   hitesh@ineuron.ai  bir
8  tulesko     400  tulesko@ineuron.ai  mum

In [22]:
data1 = {'pf_no':[234,528,458,752],
         'income_tax':[58,96,78,35],
         'mobile_no':[741258,369852,456321,456987],
         'coursed':['ds','bigdata','pyhton','blockchain']
    
}

In [24]:
df1 = pd.DataFrame(data1)

In [48]:
df

name  salary             mail_id  add
0     sudh     100     sudh@ineuron.ai  bir
1    krish     200    krish@ineuron.ai  bir
2   hitesh     300   hitesh@ineuron.ai  bir
3  tulesko     400  tulesko@ineuron.ai  mum

In [34]:
df1

pf_no  income_tax  mobile_no     coursed
0    234          58     741258          ds
1    528          96     369852     bigdata
2    458          78     456321      pyhton
3    752          35     456987  blockchain

In [49]:
pd.concat([df,df1])

name  salary             mail_id  add  pf_no  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  bir    NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  bir    NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  bir    NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum    NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN  234.0        58.0   741258.0   
1      NaN     NaN                 NaN  NaN  528.0        96.0   369852.0   
2      NaN     NaN                 NaN  NaN  458.0        78.0   456321.0   
3      NaN     NaN                 NaN  NaN  752.0        35.0   456987.0   

      coursed  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2      pyhton  
3  blockchain

In [50]:
pd.concat([df,df1],axis=1)

name  salary             mail_id  add  pf_no  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  bir    234          58     741258   
1    krish     200    krish@ineuron.ai  bir    528          96     369852   
2   hitesh     300   hitesh@ineuron.ai  bir    458          78     456321   
3  tulesko     400  tulesko@ineuron.ai  mum    752          35     456987   

      coursed  
0          ds  
1     bigdata  
2      pyhton  
3  blockchain

In [55]:
data2 = {0:['sudh','krish','hitesh','tulesko'],1:[100,200,300,400],2:['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       3:['bir','bir','bir','mum']}

In [59]:
data3 = {0:[234,528,458,752],
         1:[58,96,78,35],
         2:[741258,369852,456321,456987],
         3:['ds','bigdata','pyhton','blockchain']
    
}

In [60]:
df2 = pd.DataFrame(data2)

In [61]:
df3 = pd.DataFrame(data3)

In [63]:
pd.concat([df2,df3])

0    1                   2           3
0     sudh  100     sudh@ineuron.ai         bir
1    krish  200    krish@ineuron.ai         bir
2   hitesh  300   hitesh@ineuron.ai         bir
3  tulesko  400  tulesko@ineuron.ai         mum
0      234   58              741258          ds
1      528   96              369852     bigdata
2      458   78              456321      pyhton
3      752   35              456987  blockchain

In [64]:
pd.concat([df2,df3],axis=1)

0    1                   2    3    0   1       2           3
0     sudh  100     sudh@ineuron.ai  bir  234  58  741258          ds
1    krish  200    krish@ineuron.ai  bir  528  96  369852     bigdata
2   hitesh  300   hitesh@ineuron.ai  bir  458  78  456321      pyhton
3  tulesko  400  tulesko@ineuron.ai  mum  752  35  456987  blockchain

In [65]:
data4 = {'emp_id':[101,102,103,104],
         'salary':[200,300,400,500],
         'pf':[25,56,23,12]
        }

In [71]:
data5 = {'emp_id':[101,102,103,105],
         'mob_no':[2345,1234,5678,9874],
         'house_no':[785,425,654,963]
    
}

In [72]:
df4 = pd.DataFrame(data4)

In [73]:
df5 = pd.DataFrame(data5)

In [74]:
# it is looking for common id
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_no
0     101     200  25    2345       785
1     102     300  56    1234       425
2     103     400  23    5678       654

In [75]:
pd.merge(df4,df5,how= 'left')

emp_id  salary  pf  mob_no  house_no
0     101     200  25  2345.0     785.0
1     102     300  56  1234.0     425.0
2     103     400  23  5678.0     654.0
3     104     500  12     NaN       NaN

In [76]:
pd.merge(df5,df4,how= 'left')

emp_id  mob_no  house_no  salary    pf
0     101    2345       785   200.0  25.0
1     102    1234       425   300.0  56.0
2     103    5678       654   400.0  23.0
3     105    9874       963     NaN   NaN

In [77]:
pd.merge(df4,df5,how= 'right')

emp_id  salary    pf  mob_no  house_no
0     101   200.0  25.0    2345       785
1     102   300.0  56.0    1234       425
2     103   400.0  23.0    5678       654
3     105     NaN   NaN    9874       963

In [81]:
pd.merge(df5,df4,how= 'right',on='emp_id')

emp_id  mob_no  house_no  salary  pf
0     101  2345.0     785.0     200  25
1     102  1234.0     425.0     300  56
2     103  5678.0     654.0     400  23
3     104     NaN       NaN     500  12

In [79]:
pd.merge(df4,df5,how= 'outer')

emp_id  salary    pf  mob_no  house_no
0     101   200.0  25.0  2345.0     785.0
1     102   300.0  56.0  1234.0     425.0
2     103   400.0  23.0  5678.0     654.0
3     104   500.0  12.0     NaN       NaN
4     105     NaN   NaN  9874.0     963.0

In [80]:
pd.merge(df4,df5,how= 'cross')

emp_id_x  salary  pf  emp_id_y  mob_no  house_no
0        101     200  25       101    2345       785
1        101     200  25       102    1234       425
2        101     200  25       103    5678       654
3        101     200  25       105    9874       963
4        102     300  56       101    2345       785
5        102     300  56       102    1234       425
6        102     300  56       103    5678       654
7        102     300  56       105    9874       963
8        103     400  23       101    2345       785
9        103     400  23       102    1234       425
10       103     400  23       103    5678       654
11       103     400  23       105    9874       963
12       104     500  12       101    2345       785
13       104     500  12       102    1234       425
14       104     500  12       103    5678       654
15       104     500  12       105    9874       963

In [82]:
data4 = {'emp_id1':[101,102,103,104],
         'salary':[200,300,400,500],
         'pf':[25,56,23,12]
        }
data5 = {'emp_id2':[101,102,103,105],
         'mob_no':[2345,1234,5678,9874],
         'house_no':[785,425,654,963]
    
}

In [83]:
df6 = pd.DataFrame(data4)

In [84]:
df7 = pd.DataFrame(data5)

In [86]:
pd.merge(df6,df7)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [85]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101     200  25      101    2345       785
1      102     300  56      102    1234       425
2      103     400  23      103    5678       654

In [91]:
data8 = {'emp_id':[101,102,103,104],
         'salary':[200,300,400,500],
         'pf':[25,56,23,12]
        }
data9 = {'emp_id':[101,102,103,105],
         'salary':[200,300,400,600],
         'house_no':[785,425,654,963]
    
}

In [92]:
df8 = pd.DataFrame(data8)

In [93]:
df9 = pd.DataFrame(data9)

In [94]:
pd.merge(df8,df9)

emp_id  salary  pf  house_no
0     101     200  25       785
1     102     300  56       425
2     103     400  23       654

In [102]:
data10 = {'emp_id1':[101,102,103,104],
         'salary1':[200,300,400,500],
         'pf':[25,56,23,12]
        }
data11 = {'emp_id2':[101,102,103,105],
         'salary2':[200,300,400,600],
         'house_no':[785,425,654,963]
    
}

In [103]:
df10 = pd.DataFrame(data10,index=['a','b','c','d'])

In [104]:
df11 = pd.DataFrame(data11,index=['a','b','c','h'])

In [105]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_no
a      101      200  25    101.0    200.0     785.0
b      102      300  56    102.0    300.0     425.0
c      103      400  23    103.0    400.0     654.0
d      104      500  12      NaN      NaN       NaN

In [51]:
import pandas as pd

In [2]:
df_sales = pd.read_csv('D:/Pandas_sample/sales_data_final.csv')

In [4]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [5]:
def profit_flag(a):
    if  a>= -0:
        return 'Positive'
    else:
        return 'Negative'

In [6]:
profit_flag(-25)

'Negative'

In [7]:
profit_flag(15)

'Positive'

In [8]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [9]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    Positive  
1           9.72          Medium  2011    Positive  
2           8.17            High  2011    Positive  
3           4.82            High  2011    Negative  
4           4.70          Medium  2011    Positive  

[5 rows x 22 columns]

In [10]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [11]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     Positive            15  
1           9.72          Medium  2011     Positive            11  
2           8.17            High  2011     Positive            13  
3           4.82            High  2011     Negative            12  
4           4.70          Medium  2011     Positive            11  

[5 rows x 23 columns]

In [12]:
def quantity_flag(a):
    if a < 10:
        return 'Low'
    elif a > 10 and a < 20:
        return 'Medium'
    else:
        return 'High'

In [13]:
df_sales['quantity_flag'] = df_sales['quantity'].apply(quantity_flag)

In [14]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     Positive   
1        3      0.1   36.036          9.72          Medium  2011     Positive   
2        4      0.0   29.640          8.17            High  2011     Positive   
3        3      0.5  -26.055          4.82            High  2011     Negative   
4        5      0.1   37.770          4.70          Medium  2011     Positive   

   len_cust_name quantity_flag  
0             15           Low  
1             11           Low  
2             13           Low  
3             12           Low  
4             11           Low  

[5 rows x 24 columns]

In [15]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)

In [16]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   

   len_cust_name  quantity_flag square_quantity  
0             15            Low               4  
1             11            Low               9  
2             13            Low              16  
3             12            Low               9  
4             11            Low              25  

[5 rows x 25 columns]

In [17]:
import numpy as np

In [18]:
np.array([2,4,6,7,8,9])

array([2, 4, 6, 7, 8, 9])

In [20]:
type(np.array([2,4,6,7,8,9]))

numpy.ndarray

In [24]:
np.array([[1,2,3,4,5],[5,8,6,9,4]])

array([[1, 2, 3, 4, 5],
       [5, 8, 6, 9, 4]])

In [25]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
l = [[1,2,3,4],[2,3,4,5]]

In [27]:
l[0][0]

1

In [33]:
a = np.array([5,8,6,4,9] , ndmin = 15)

In [34]:
a

array([[[[[[[[[[[[[[[5, 8, 6, 4, 9]]]]]]]]]]]]]]])

In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.ndim

2

In [41]:
np.random.randint(1,10,(4,4))

array([[4, 1, 2, 7],
       [3, 8, 3, 3],
       [5, 9, 3, 4],
       [3, 4, 9, 3]])

In [42]:
np.random.randint(1,10,(4,4,2))

array([[[5, 5],
        [9, 2],
        [9, 4],
        [3, 9]],

       [[3, 9],
        [8, 6],
        [5, 7],
        [5, 9]],

       [[1, 9],
        [7, 2],
        [3, 7],
        [1, 3]],

       [[9, 5],
        [4, 7],
        [6, 1],
        [3, 6]]])